# Generated by Django 5.2.1 on 2025-06-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
